{% set version = "2.0.1" %}

package:
  name: gpflow
  version: {{ version }}

source:
  fn: GPflow-{{ version }}.tar.gz
  url: https://github.com/GPflow/GPflow/archive/v{{ version }}.tar.gz
  sha256: ade68068a19f5226e03c2a009e57f8fdc83d21f3b0de969bec90e05e829c89bc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py2k]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.10.0
    - scipy >=0.18.0
    - pandas >=0.18.1
    - tensorflow
    - multipledispatch >=0.4.9
    - pytest >=3.5.0
    - h5py >=2.7.0

test:
  imports:
    # Skip the import test, see tensorflow recipe
    - gpflow  # [not unix]

about:
  home: https://github.com/GPflow/GPflow/
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: Gaussian process methods in tensorflow

extra:
  recipe-maintainers:
    - cxhernandez
    - jschueller
