{% set name = "gpflow" %}
{% set version = "2.11.1" %}

package:
  name: gpflow
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/gpflow-{{ version }}.tar.gz
  sha256: 722666a52734e5dba7eaf4b3e2b4483a67026cd7571c65eb83bfda8a9009ef81

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - setuptools >=41.0.0
    - wheel
    - python {{ python_min }}
  run:
    - check_shapes >=1.0.0
    - deprecated
    - lark >=1.1.0
    - multipledispatch >=0.6
    - numpy
    - packaging
    - python >={{ python_min }}
    - scipy
    - setuptools >=41.0.0
    - tabulate
    - tensorflow >=2.4.0
    - tensorflow-probability >=0.12.0
    - typing-extensions
    - tf-keras
test:
  imports:
    - gpflow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/GPflow/GPflow/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Gaussian processes in TensorFlow

extra:
  recipe-maintainers:
    - westinhuang
    - cxhernandez
