{% set name = "gpflow" %}
{% set version = "2.6.2" %}

package:
  name: gpflow
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gpflow-{{ version }}.tar.gz
  sha256: f6c72b6fed8cc18b863862eb5b86d81fba2c93a7e4796c528669f8311d0e5a32

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - deprecated
    - lark >=1.1.0
    - multipledispatch >=0.6
    - numpy
    - packaging
    - python >=3.7
    - scipy
    - setuptools >=41.0.0
    - tabulate
    - tensorflow >=2.4.0
    - tensorflow-probability >=0.12.0
    - typing-extensions

test:
  imports:
    - gpflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/GPflow/GPflow/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Gaussian processes in TensorFlow

extra:
  recipe-maintainers:
    - cxhernandez
