{% set version = "1.4.0" %}

package:
  name: gpflow
  version: {{ version }}

source:
  fn: GPflow-{{ version }}.tar.gz
  url: https://github.com/GPflow/GPflow/archive/v{{ version }}.tar.gz
  sha256: 0264f686c90af07ce91a2ad1c9d6599f3c85d4077220c59d67604db87a9fb6d0

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  skip: true  # [py2k]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.10.0
    - scipy >=0.18.0
    - pandas >=0.18.1
    - tensorflow
    - multipledispatch >=0.4.9
    - pytest >=3.5.0
    - h5py >=2.7.0

test:
  imports:
    # Skip the import test, see tensorflow recipe
    - gpflow  # [not unix]

about:
  home: https://github.com/GPflow/GPflow/
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: Gaussian process methods in tensorflow

extra:
  recipe-maintainers:
    - cxhernandez
    - jschueller
