{% set version = "2.0.2" %}

package:
  name: gpflow
  version: {{ version }}

source:
  fn: GPflow-{{ version }}.tar.gz
  url: https://github.com/GPflow/GPflow/archive/v{{ version }}.tar.gz
  sha256: 644d4e278423d0fdeaf4783355a08adfdc7d3a2f1d496b16e621afddd3b4e439

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - pandas >=0.18.1
    - tensorflow >=2.1.0,<3
    - tensorflow-probability >0.10.0,<1
    - multipledispatch >=0.6
    - tabulate
    - typing_extensions
    - packaging

test:
  imports:
    - gpflow

about:
  home: https://github.com/GPflow/GPflow/
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: Gaussian process methods in tensorflow

extra:
  recipe-maintainers:
    - cxhernandez
    - jschueller
