{% set version = "2.0.0" %}

package:
  name: gpflow
  version: {{ version }}

source:
  fn: GPflow-{{ version }}.tar.gz
  url: https://github.com/GPflow/GPflow/archive/v{{ version }}.tar.gz
  sha256: 90f1225049b57e1803e61c48442d5ae2cb13c195a8928972da020c645592fcb7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py2k]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.10.0
    - scipy >=0.18.0
    - pandas >=0.18.1
    - tensorflow
    - multipledispatch >=0.4.9
    - pytest >=3.5.0
    - h5py >=2.7.0

test:
  imports:
    # Skip the import test, see tensorflow recipe
    - gpflow  # [not unix]

about:
  home: https://github.com/GPflow/GPflow/
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: Gaussian process methods in tensorflow

extra:
  recipe-maintainers:
    - cxhernandez
    - jschueller
