travis:
  secure:
    BINSTAR_TOKEN: xok5Kwgb0afLzgpyFQOlGrT24GLV5PIBr0s94OB4QsfK3xjMKbNL7/p7q0EVoZ4bm2GecIAxkQL2/5xRJBJFG+Lmko7HJD0h3CadSIKSN4+5696bOLk5GAMFbYPqM6DcOp4qy/LwCfJ3GHPF4VqMLA+2gDfteKdwwi4JVGDUQ7kEZzwUnyzyK9cgZ5NcxHPqJmw1VF27RTxHB+ml9WXA0mM8Ue5ZUZ+lCVHem/0CZ1kPmMnsB211g9jLBN3fTX3n/iojRnCqWMEUvhhnA4yfDiqxBvtT0DUBw35rqJVmtc5pp8ojCw8ikKXlrGVOvUonzjrZK5ZdL7STtDyiQ0CUE6YpcEpOFRClv3HmWBp0cfKBShleGv61nCKxOamg2mYtRGC2gIjxk2ZwDI4iPDzFvi7onDnrl7DBNVMC1YseqZrlU2MyM+9tcfCHFaHUV+9PEwNgZPoFccNtC4zU8dqFQJaGJqIci4ddbXLDZzp8Kuhm4BnUHcCA0tTki1U6wVbmWGqHMvvwKXOICJ2lmDBU1A8r5hAcJOZONFTzTIs3j1sRbYLif85zuUAjx8RuD+zEL9BdUlOHXdju5QhgOI3EwuqMlPGn8S7e/ISpmqPn4tChWGCFHF8NqXYMzT+BNr+NHOkC8mDYDVp9jXUzWGOB/kVvVxLRKqLUhH2Hh44+0kE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
channel_priority: flexible
